version: "3"
services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - "5001:7001"
      - "9999:9999"
    volumes:
      - .:/usr/src/app
    restart: always
  db:
    image: mongo
    ports:
      - "27017:27017"
